os:
- linux
sudo: required
language: c
services:
- docker
before_install:
- docker build -t ring3/ocaml .
- docker images
  # - rvm use ruby-2.2.3
script:
- chmod -R o+w src/
- docker run -t -t -v $PWD:/mnt ring3/ocaml make -C /mnt
- sudo chown travis.travis src/test-vm.xen.gz
- ls -lh src/
deploy:
  provider: releases
  api_key:
    secure: EgP6w6c32LQtMGUxHDpYS5+l9j+a9idW8vYHd6QI1F8sVr2VpHT89Lby61ok+AC7Apt1z0gH+BuA7BKZRX2belA0oO58jJqFHZiB91iYWvFcvQNpKSz+E4Fp64RgYzAOV4jn369degqSoNbhGLb4oU1uaGhXZopprcmPZ4SMMC+WM2egcncT4Vt+VJ/nFQroev+fTFqMVDu737djwtT8GIQwoRKLFlAq1ZlSBBUECwUXThHAlOTT2pjbYUioR9/V6PvavxPrOzkozu+tnx1GrowESydvLIpTPGss3GccJpIsRHviE5YPDHhlI3O+vyHTl6POT3LrtiivIp/hW+sVg+3hfYPEtxXwgifminbKT0pbg3GKJu60IQznP56igL3yPclrq2UU8iYCHfe/tJSuse5GKVBqHoe+SNqX/IvqYgtR/S+d+M2DsHV8joXUm+ryvO/U6FgSRzAJgi5ekbdGsF+138biJKEXGG1Ma9fPn3FUbFy/Hg80cB6ABrFdXPOSvls5SHZqygARqoPJOIw1+RO0KyCAG9dGjd+Db9kFhPluiaeXY5rXDK9EOk4W38DnuSAwnVnIyLaSFD49nnUQw8qOjlOXGvmFD3cjJpn9VW7Zoh34qYfVBsGywIVCHjkbeJ9/xtaERznOWunReGX2jq9GemLE0OKoTK170iPUDsY=
  file: src/test-vm.xen.gz
  skip_cleanup: true
  on:
    tags: true
